# -*- coding: utf-8 -*-
"""Module_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiQUn1DG4Gd8bFGdIhbfvBGBk6ANY8vy

Part A -
Profiling, cleaning, and the data story
"""

import seaborn as sns
import pandas as pd

df = sns.load_dataset('titanic')
print(df.info())
print(df.describe())
print(df.shape)

df.to_csv("titanic.csv", index=False)

# Compute % missing per column and show only columns with missing values
missing_pct = df.isna().mean() * 100
missing_pct = missing_pct[missing_pct > 0]

print(missing_pct)

#1 — drop rows for the low-missing columns
df = df.dropna(subset=['embarked','embark_town'])

from numpy import median
#task 2 — impute age (5-30% band)
df['age'] = df['age'].fillna(df['age'].median())

df = df.drop(columns = ['deck'])

df

df.info()

import matplotlib.pyplot as plt
#task 3
df['age'].hist(bins=30)
plt.title('Age Distribution')
plt.show()

df['fare'].hist(bins=30)
plt.title('Fare Distribution')
plt.show()

df.boxplot(column = 'age')
plt.title('Age Box Plot')
plt.show()

df.boxplot(column = "fare")
plt.title('Fare Box Plot')
plt.show()

#task 4
def count_outliers_iqr(df,column):
  Q1 = df[column].quantile(0.25)
  Q3 = df[column].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5*IQR
  upper_bound = Q3 + 1.5*IQR
  outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
  return len(outliers)

print("Age outliers:", count_outliers_iqr(df,'age'))
print("Fare outliers:",count_outliers_iqr(df,'fare'))

fare_mean = df['fare'].mean()
fare_median = df['fare'].median()
fare_mode = df['fare'].mode()[0]
print(f"Mean: {fare_mean}, Median: {fare_median}, Mode: {fare_mode}")

male_survival_rate = df[df['sex']=='male']['survived'].mean()
female_survival_rate = df[df['sex']=='female']['survived'].mean()
print(f"Male survival rate: {male_survival_rate}")
print(f"Female survival rate: {female_survival_rate}")

class1_survival = df[df['pclass'] == 1]['survived'].mean()
class2_survival = df[df['pclass'] == 2]['survived'].mean()
class3_survival = df[df['pclass'] == 3]['survived'].mean()
print(class1_survival)
print(class2_survival)
print(class3_survival)

female_class1 = df[(df['sex'] == 'female') & (df['pclass'] == 1)]['survived'].mean()
print(female_class1)

female_class2 = df[(df['sex'] == 'female') & (df['pclass'] == 2)]['survived'].mean()
female_class3 = df[(df['sex'] == 'female') & (df['pclass'] == 3)]['survived'].mean()
male_class1 = df[(df['sex'] == 'male') & (df['pclass'] == 1)]['survived'].mean()
male_class2 = df[(df['sex'] == 'male') & (df['pclass'] == 2)]['survived'].mean()
male_class3 = df[(df['sex'] == 'male') & (df['pclass'] == 3)]['survived'].mean()

print(female_class2)
print(female_class3)
print(male_class1)
print(male_class2)
print(male_class3)

corr_columns = ['survived','pclass','age','sibsp','parch','fare']
corr_matrix = df[corr_columns].corr()
print(corr_matrix)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

sns.barplot(x='sex', y='survived', data=df)
plt.title('Survival Rate by Sex')
plt.ylabel('Survival Rate')
plt.show()

sns.barplot(x='pclass', y='survived', data=df)
plt.title('Survival Rate by Passenger Class')
plt.show()

sns.barplot(x='pclass', y='survived', hue='sex', data=df)
plt.title('Survival Rate by Class and Sex')
plt.show()

sns.boxplot(x='survived', y='age', data=df)
plt.title('Age Distribution by Survival')
plt.show()

print("Before standardization: ")
print(df[['age','fare']].describe().loc[['mean','std']])

df['age_zscore'] = (df['age'] - df['age'].mean())/df['age'].std()
df['fare_zscore'] = (df['fare'] - df['fare'].mean())/df['fare'].std()

print("After standardization:")
print(df[['age_zscore',  'fare_zscore']].describe().loc[['mean', 'std']])

"""Part B -  Predictive modeling, continuing from the same cleaned data"""

import pandas as pd
df = pd.read_csv("titanic.csv")

import pandas as pd

df = pd.read_csv("titanic.csv")

# reapply Task 2 cleaning
df = df.dropna(subset=['embarked', 'embark_town'])
df['age'] = df['age'].fillna(df['age'].median())
df = df.drop(columns=['deck'])

print(df.shape)
print(df.isna().sum())

from sklearn.model_selection import train_test_split

X = df.drop(columns=['survived'])
y = df['survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train survival rate: ", y_train.mean())
print("Test survival rate: ",y_test.mean())

print(X_train.dtypes)

drop_cols = ['class','who','adult_male','embark_town','alive','alone']
X_train = X_train.drop(columns = drop_cols)
X_test = X_test.drop(columns = drop_cols)

numeric_features = ['pclass','age','sibsp','parch','fare']
categorical_features = ['sex','embarked']

print(X_train.columns.tolist())

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers = [
    ('num',numeric_transformer,numeric_features),
    ('cat',categorical_transformer,categorical_features)
])

X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)
print(X_train_transformed.shape)
print(X_test_transformed.shape)

"""Task: Train the three classifiers

1 — Logistic Regression pipeline
"""

from sklearn.linear_model import LogisticRegression

log_reg_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])
log_reg_pipeline.fit(X_train, y_train)

"""2 — Decision Tree pipeline"""

from sklearn.tree import DecisionTreeClassifier

dt_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42))
])
dt_pipeline.fit(X_train, y_train)

"""3 — Random Forest pipeline"""

from sklearn.ensemble import RandomForestClassifier

rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])
rf_pipeline.fit(X_train, y_train)

print(log_reg_pipeline.score(X_test,y_test))
print(dt_pipeline.score(X_test,y_test))
print(rf_pipeline.score(X_test,y_test))

feature_names = preprocessor.get_feature_names_out()
print(feature_names)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 10))
plot_tree(
    dt_pipeline.named_steps['classifier'],
    feature_names=preprocessor.get_feature_names_out(),
    class_names=['Not Survived', 'Survived'],
    filled=True,
    max_depth=3
)
plt.show()

from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score, roc_curve
)

def evaluate_model(pipeline, X_test, y_test, model_name):
    y_pred = pipeline.predict(X_test)
    y_proba = pipeline.predict_proba(X_test)[:, 1]  # probability of class 1 (survived)

    cm = confusion_matrix(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_proba)

    print(f"--- {model_name} ---")
    print("Confusion Matrix:\n", cm)
    print(f"Accuracy: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1: {f1:.4f}, AUC: {auc:.4f}")

    return {'model': model_name, 'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1, 'auc': auc}

results = []
results.append(evaluate_model(log_reg_pipeline, X_test, y_test, "Logistic Regression"))
results.append(evaluate_model(dt_pipeline, X_test, y_test, "Decision Tree"))
results.append(evaluate_model(rf_pipeline, X_test, y_test, "Random Forest"))

results_df = pd.DataFrame(results)
print(results_df)

from sklearn.metrics import roc_curve

plt.figure(figsize=(8, 6))

for pipeline, name in [(log_reg_pipeline, 'Logistic Regression'),
                         (dt_pipeline, 'Decision Tree'),
                         (rf_pipeline, 'Random Forest')]:
    y_proba = pipeline.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    plt.plot(fpr, tpr, label=name)

plt.plot([0, 1], [0, 1], 'k--', label='Random guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves')
plt.legend()
plt.show()

print(y_train.value_counts())
print(y_train.value_counts(normalize=True))

rf_balanced_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, class_weight='balanced'))
])
rf_balanced_pipeline.fit(X_train, y_train)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

rf_smote_pipeline = ImbPipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('classifier', RandomForestClassifier(random_state=42))
])
rf_smote_pipeline.fit(X_train, y_train)

results.append(evaluate_model(rf_smote_pipeline, X_test, y_test, "RF + SMOTE"))

results_df = results_df.drop_duplicates(subset='model').reset_index(drop=True)
print(results_df)

rf_for_tuning = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, oob_score=True, bootstrap=True))
])

param_grid = {
    'classifier__n_estimators': [100, 200, 300],
    'classifier__max_depth': [5, 10, None],
    'classifier__max_features': ['sqrt', 'log2']
}

from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(rf_for_tuning, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

print("Best params:", grid_search.best_params_)

print("Best params:", grid_search.best_params_)
print("Best CV accuracy:", grid_search.best_score_)

best_rf_pipeline = grid_search.best_estimator_
oob = best_rf_pipeline.named_steps['classifier'].oob_score_
print("OOB score:", oob)

X_reg = df.drop(columns=['fare'])
y_reg = df['fare']

# also drop the same redundant columns as before, if not already dropped in df
X_reg = X_reg.drop(columns=[c for c in ['class','who','adult_male','embark_town','alive','alone'] if c in X_reg.columns])

X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

numeric_features_reg = ['pclass', 'age', 'sibsp', 'parch']
categorical_features_reg = ['sex', 'embarked']

preprocessor_reg = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features_reg),
    ('cat', categorical_transformer, categorical_features_reg)
])

from sklearn.linear_model import LinearRegression

reg_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor_reg),
    ('regressor', LinearRegression())
])
reg_pipeline.fit(X_reg_train,y_reg_train)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_reg_pred = reg_pipeline.predict(X_reg_test)

mae = mean_absolute_error(y_reg_test, y_reg_pred)
rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))
r2 = r2_score(y_reg_test, y_reg_pred)

print(f"MAE: {mae:.4f}, RMSE: {rmse:.4f}, R²: {r2:.4f}")

n = len(y_reg_test)
p = X_reg_test.shape[1]   # number of original predictor columns
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
print(f"Adjusted R²: {adj_r2:.4f}")

residuals = y_reg_test - y_reg_pred

plt.figure(figsize=(8, 6))
plt.scatter(y_reg_pred, residuals, alpha=0.5)
plt.axhline(y=0, color='r', linestyle='--')
plt.xlabel('Predicted Fare')
plt.ylabel('Residuals')
plt.title('Residual Plot')
plt.show()

print("=== Classification Models ===")
print(results_df[['model', 'accuracy', 'precision', 'recall', 'f1', 'auc']])

print("\n=== Regression Model (Fare Prediction) ===")
print(f"MAE: {mae:.4f}, RMSE: {rmse:.4f}, R²: {r2:.4f}, Adjusted R²: {adj_r2:.4f}")

import joblib

joblib.dump(best_rf_pipeline, 'titanic_survival_pipeline.pkl')
print("Pipeline saved.")

loaded_pipeline = joblib.load('titanic_survival_pipeline.pkl')
sample_prediction = loaded_pipeline.predict(X_test.iloc[:5])
print("Sample predictions from reloaded pipeline:", sample_prediction)