# -*- coding: utf-8 -*-
"""Module_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yMjPYlNWkhUHe7-nrgklF3_xMKXd0fZ

Task 1
"""

import requests
from bs4 import BeautifulSoup

def fetch_page(url):
  response = requests.get(url)
  response.encoding = 'utf-8'
  html = response.text
  soup = BeautifulSoup(html,'html.parser')
  return soup

def get_book_cards(soup):
  books = soup.find_all('article',class_='product_pod')
  return books

def extract_book_data(card,category):
  title = card.find('h3').find('a')['title']
  price = card.find('p',class_ = 'price_color').text
  star_rating = card.find('p',class_ = 'star-rating')['class'][1]
  availability = card.find('p',class_ = 'instock availability').text.strip()

  return {
      'title':title,
      'price':price,
      'star_rating':star_rating,
      'availability':availability,
      'category':category
  }

def build_page_url(category_url,page):
  if page == 1:
    return category_url
  else:
    return category_url.replace("index.html",f"page-{page}.html")

def scrape_category(category_url,category,max_pages = 50):
  all_books = []
  page = 1
  while page <= max_pages:
    url = build_page_url(category_url,page)
    soup = fetch_page(url)
    if soup is None:
      break
    cards = get_book_cards(soup)
    for card in cards:
      all_books.append(extract_book_data(card, category))
    page += 1
  return all_books

categories = {
    "Travel" : "https://books.toscrape.com/catalogue/category/books/travel_2/index.html",
    "Poetry" : "https://books.toscrape.com/catalogue/category/books/poetry_23/index.html",
    "Mystery" : "https://books.toscrape.com/catalogue/category/books/mystery_3/index.html",
    "History Fiction": "https://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html"
}

def scrape_all(categories):
  all_books = []
  for category_name,url in categories.items():
    books = scrape_category(url,category_name)
    all_books.extend(books)
  return all_books

import pandas as pd
all_books_raw = scrape_all(categories)
df = pd.DataFrame(all_books_raw)
print(df.shape)
print(df['category'].value_counts())
print(df.head())

"""Task 2"""

def clean_price(raw_price):
  try:
    price = float(raw_price.strip("£").strip(" "))
    return price
  except:
    return None

Rating_Map = {
    "One" : 1,
    "Two":2,
    "Three":3,
    "Four":4,
    "Five":5
}
def clean_rating(raw_rating):
    return Rating_Map.get(raw_rating, None)

def clean_availability(raw_availability):
  if "in stock" in raw_availability.lower():
    return True
  else:
    return False

import pandas as pd
all_books_raw = scrape_all(categories)
df = pd.DataFrame(all_books_raw)
df['price_gbp'] = df['price'].apply(clean_price)
df['rating'] = df['star_rating'].apply(clean_rating)
df['in stock'] = df['availability'].apply(clean_availability)

print(df['price_gbp'].isna().sum())
print(df['rating'].isna().sum())

df = df.rename(columns={'in stock': 'in_stock'})

"""Task 3"""

df['price_inr'] = df['price_gbp']*105.50
print(df[['title', 'price_gbp', 'price_inr', 'rating', 'in_stock', 'category']].head())
print(df.dtypes)

"""Task 4"""

import sqlite3

def create_schema(db_path = 'books.db'):
  conn = sqlite3.connect(db_path)
  cursor = conn.cursor()
  cursor.execute('''
                CREATE TABLE IF NOT EXISTS categories (
                    category_id INTEGER PRIMARY KEY,
                    category_name TEXT UNIQUE
                )
                ''')
  cursor.execute('''
                CREATE TABLE IF NOT EXISTS books (
                    book_id INTEGER PRIMARY KEY,
                    title TEXT,
                    price_gbp REAL,
                    price_inr REAL,
                    rating INT,
                    in_stock INT,
                    category_id INT REFERENCES categories(category_id)
                )
                ''')
  conn.commit()
  return conn

conn = create_schema('books.db')
print("Schema created successfully")
conn.close()

def insert_categories(conn,df):
  cursor = conn.cursor()
  unique_categories = df['category'].unique()

  for cat in unique_categories:
    cursor.execute("INSERT OR IGNORE INTO categories (category_name) VALUES (?)", (cat,))
  conn.commit()

  cursor.execute("SELECT category_id, category_name FROM categories")
  rows = cursor.fetchall()

  category_map = {}
  for key, value in rows:
    category_map[value]= key
  return category_map

conn = create_schema('books.db')
category_map = insert_categories(conn, df)
print(category_map)

def insert_books(conn, df, category_map):
    cursor = conn.cursor()
    for index, row in df.iterrows():
        cat_id = category_map[row['category']]
        cursor.execute('''
            INSERT INTO books (title, price_gbp, price_inr, rating, in_stock, category_id)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (row['title'], row['price_gbp'], row['price_inr'], row['rating'], row['in_stock'], cat_id))
    conn.commit()

insert_books(conn, df, category_map)
cursor = conn.cursor()
cursor.execute("SELECT COUNT(*) FROM books")
print(cursor.fetchone())

"""Task 5

1 Query
"""

cursor.execute('''
    SELECT b.title, b.price_gbp, c.category_name
    FROM books b JOIN categories c ON b.category_id = c.category_id
    LIMIT 5
''')
print(cursor.fetchall())

"""2 Query"""

cursor.execute('''
    SELECT title, price_gbp, in_stock
    FROM books
    WHERE in_stock = 1
    ORDER BY price_gbp ASC
    LIMIT 10
''')
results = cursor.fetchall()
print(results)

"""3 Query"""

cursor.execute('''
    SELECT DISTINCT category_name
    FROM categories
''')
print(cursor.fetchall())

"""4 Query"""

cursor.execute('''
    SELECT title, rating
    FROM books
    WHERE rating IN (4, 5)
''')
print(cursor.fetchall())

cursor.execute('''
    SELECT b.title, b.rating, c.category_name
    FROM books b
    JOIN categories c ON b.category_id = c.category_id
    ORDER BY b.rating DESC
''')
print(cursor.fetchall())

print(df['price_gbp'].describe())

"""5 Query"""

cursor.execute('''
    SELECT title, price_gbp
    FROM books
    WHERE price_gbp BETWEEN 20 AND 49
''')
print(cursor.fetchall())

"""Task 6"""

import pandas as pd

df_instock_query = pd.read_sql('''
    SELECT title, price_gbp, in_stock
    FROM books
    WHERE in_stock = 1
    ORDER BY price_gbp ASC
    LIMIT 5
''', conn)

print(df_instock_query)

import pandas as pd

df_books_between = pd.read_sql('''
    SELECT title, price_gbp
    FROM books
    WHERE price_gbp BETWEEN 20 AND 49
''', conn)

print(df_books_between)

books_df = pd.read_sql("SELECT * FROM books", conn)
categories_df = pd.read_sql("SELECT * FROM categories", conn)

merged_df = pd.merge(books_df, categories_df, on='category_id')
print(merged_df.sort_values('rating',ascending = False))